In [2]:
import pickle as pkl
import pandas as pd
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
from tqdm import tqdm
from itertools import chain
from scipy import sparse

with open('Data/training_data.pkl', 'rb') as file:
    train_graphs = pkl.load(file)

dict_values([[1], [1], [2], [0], [0], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]])
[1, 1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [51]:
#Alphabet instances for each graph over all hops
#List of N empty lists
N = len(train_graphs)
vertexlabs = np.zeros((N, 50))
edgelabs = np.zeros((N, 4))
for i in range(N):
    va = nx.get_node_attributes(train_graphs[i], 'labels').values()
    va = list(chain.from_iterable(va))
    vb = np.c_[np.unique(va, return_counts=1)]
    vertexlabs[i, vb[:,0]] = vb[:,1]
    ea = nx.get_edge_attributes(train_graphs[i], 'labels').values()
    ea = list(chain.from_iterable(ea))
    eb = np.c_[np.unique(ea, return_counts=1)]
    if len(eb!=0): #completely disconnected graph
        edgelabs[i, eb[:,0]] = eb[:, 1]

# L = pd.DataFrame(vertexlabs, columns=[f'v{i}' for i in range(50)]+[f'e{i}' for i in range(4)])


[2, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2]
[[ 0 10]
 [ 2  6]]
[2, 2, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 1, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0]
[[ 0  7]
 [ 1  1]
 [ 2 17]]
[0, 1, 0, 0, 0, 0, 2, 2, 0, 0, 0, 2, 2, 2, 0, 2, 0, 0, 0]
[[ 0 12]
 [ 1  1]
 [ 2  6]]
[2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 0, 1, 1, 0, 1, 0, 0, 0, 2, 2, 2, 2, 0, 2, 2, 1, 0, 0, 0, 0]
[[ 0 15]
 [ 1  4]
 [ 2 18]]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0]
[[ 0 30]
 [ 1  5]]
[0, 0, 1, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1]
[[ 0  7]
 [ 1  2]
 [ 2 12]]
[2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 2, 2, 0, 2, 1, 2, 2, 2]
[[ 0  6]
 [ 1  2]
 [ 2 12]]
[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[ 0 18]
 [ 1  1]]
[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0]
[[ 0 15]
 [ 1  5]]
[0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0]
[[ 0 31]
 [ 1  8]]
[0

IndexError: arrays used as indices must be of integer (or boolean) type

In [55]:
len(eb)

0

In [48]:
# va = list(chain.from_iterable(nx.get_edge_attributes(train_graphs[i], 'labels').values()))
# vb = np.c_[np.unique(va, return_counts=1)]
# print(va)

# np.unique(va, return_counts=1)
[f'v{i}' for i in range(50)]+[f'e{i}' for i in range(4)]

['v0', 'v1', 'v2', 'v3', 'v4', 'e0', 'e1', 'e2', 'e3']

In [37]:
nx.get_node_attributes(train_graphs[i], 'labels')

{0: [2],
 1: [13],
 2: [1],
 3: [5],
 4: [5],
 5: [0],
 6: [0],
 7: [0],
 8: [1],
 9: [1],
 10: [1],
 11: [1],
 12: [1],
 13: [1]}